# Generated by Django 4.1.2 on 2022-10-11 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='description',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='thing',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=100, message='Value must not be higher than 100.'), django.core.validators.MinValueValidator(limit_value=0, message='Value must not be lower than 0.')]),
        ),
    ]
